"""Generating Dovecot's configuration.

Lightr owns this configuration rather than documenting it, because
"install the package and it works" is the difference between a mail
engine and a pile of parts. The generated files are reviewed as
carefully as the Python: they decide where mail is stored and who may
read it.

Two artefacts:

``dovecot.conf``
    A drop-in for ``/etc/dovecot/conf.d/``, wiring Maildir, LMTP,
    Sieve, quota, and the Lua auth backend.

``lightr-auth.lua``
    The passdb/userdb script. It calls Lightr's internal endpoints so
    that IMAP logins go through the same authentication path as
    everything else -- which is what makes LDAP/OAuth2/OIDC offload
    work for IMAP without a second implementation.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass
from pathlib import Path

from lightr.config import Config

LUA_SCRIPT_NAME = "lightr-auth.lua"
CONF_NAME = "99-lightr.conf"


class DovecotConfigError(ValueError):
    """The configuration could not be generated."""


#: Dovecot's auth process runs as this user, and has to read the files
#: that carry the credentials it authenticates with.
DOVECOT_GROUP = "dovecot"


@dataclass(frozen=True, slots=True)
class GeneratedFile:
    path: Path
    content: str
    mode: int = 0o644
    group: str | None = None

    @property
    def is_secret(self) -> bool:
        """Whether the file carries a credential.

        Owner-plus-group, not owner-only: Dovecot's auth process runs
        as the dovecot user, so a file it must read cannot be 0600
        root:root. Restricting it to the group is the tightest setting
        that still works.
        """
        return not self.mode & 0o007


def generate_internal_key() -> str:
    """A shared secret for the Lua script to present to Lightr."""
    return secrets.token_urlsafe(32)


def lua_script(cfg: Config, api_base_url: str) -> str:
    """The passdb/userdb Lua script.

    Dovecot's Lua backend gets two entry points. Both call Lightr over
    HTTP; neither ever touches the database directly, which is the
    whole point -- Lightr decides, using whatever provider the account
    is configured for.
    """
    key = cfg.dovecot.internal_key
    if not key:
        raise DovecotConfigError(
            "dovecot.internal_key is not set -- run `lightr dovecot setup` first"
        )

    return f'''--
-- Generated by Lightr. Do not edit -- regenerate with:
--     lightr dovecot config
--
-- Authenticates against Lightr rather than against the database, so
-- offloaded providers (LDAP, OAuth2, OIDC, webhook) work for IMAP too.
--

local http_client = nil

local API_BASE = "{api_base_url}"
local INTERNAL_KEY = "{key}"
local TIMEOUT_MS = 5000

function auth_init()
  http_client = dovecot.http.client {{
    timeout = TIMEOUT_MS,
    max_attempts = 2,
  }}
  return 0
end

local function post(path, body)
  local request = http_client:request {{
    url = API_BASE .. path,
    method = "POST",
  }}
  request:add_header("Content-Type", "application/json")
  request:add_header("X-Lightr-Internal-Key", INTERNAL_KEY)
  request:set_payload(body)
  return request:submit()
end

local function json_escape(value)
  return value:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"')
end

local function field(payload, name)
  return payload:match('"' .. name .. '"%s*:%s*"([^"]*)"')
end

function auth_passdb_lookup(req)
  local body = string.format(
    '{{"username":"%s","password":"%s"}}',
    json_escape(req.user), json_escape(req.password)
  )
  local ok, response = pcall(post, "/internal/auth/verify", body)
  if not ok then
    return dovecot.auth.PASSDB_RESULT_INTERNAL_FAILURE, "lightr unreachable"
  end

  local status = response:status()
  if status == 200 then
    return dovecot.auth.PASSDB_RESULT_OK, ""
  elseif status == 401 then
    -- Deliberately the same answer for a wrong password and an
    -- unknown account, so this cannot be used to enumerate addresses.
    return dovecot.auth.PASSDB_RESULT_PASSWORD_MISMATCH, ""
  end
  -- 403/503 and anything else: a problem on our side, not the user's.
  return dovecot.auth.PASSDB_RESULT_INTERNAL_FAILURE, "lightr returned " .. status
end

function auth_userdb_lookup(req)
  local body = string.format('{{"username":"%s"}}', json_escape(req.user))
  local ok, response = pcall(post, "/internal/auth/user", body)
  if not ok then
    return dovecot.auth.USERDB_RESULT_INTERNAL_FAILURE, "lightr unreachable"
  end

  local status = response:status()
  if status == 404 then
    return dovecot.auth.USERDB_RESULT_USER_UNKNOWN, ""
  elseif status ~= 200 then
    return dovecot.auth.USERDB_RESULT_INTERNAL_FAILURE, "lightr returned " .. status
  end

  local payload = response:payload()
  local home = field(payload, "home")
  local mail = field(payload, "mail")
  local quota = field(payload, "quota_rule")

  local attrs = {{}}
  if home then table.insert(attrs, "home=" .. home) end
  if mail then table.insert(attrs, "mail=" .. mail) end
  if quota then table.insert(attrs, "quota_rule=" .. quota) end

  return dovecot.auth.USERDB_RESULT_OK, table.concat(attrs, " ")
end

function auth_userdb_iterate()
  -- Lightr owns the account list; iteration is not supported here.
  return {{}}
end
'''


def dovecot_conf(cfg: Config, lua_path: Path) -> str:
    """The Dovecot drop-in.

    Maildir with no ``mail_attachment_dir``: single-instance attachment
    storage is deprecated and its failure mode is missing attachments,
    which is the worst outcome this engine can have.
    """
    dovecot = cfg.dovecot
    maildir = dovecot.maildir_root.as_posix()
    # Named relative to Dovecot's base_dir, not as an absolute path.
    # Dovecot's stock 10-master.conf already declares `unix_listener
    # lmtp`; an absolute path here resolves to the same socket but
    # counts as a second declaration, and Dovecot refuses to start with
    # "duplicate listener". The relative name merges with the stock one
    # instead, which is what we want -- we are only changing its mode
    # and ownership.
    lmtp_socket = (
        dovecot.lmtp_socket.as_posix() if dovecot.lmtp_socket else "/run/dovecot/lmtp"
    )
    lmtp_listener = Path(lmtp_socket).name if lmtp_socket.startswith(
        ("/run/dovecot/", "/var/run/dovecot/")
    ) else lmtp_socket

    sieve_dir = dovecot.sieve_dir.as_posix()
    # Dovecot requires this on a single line, however long it gets.
    sieve_setting = (
        f"file:{sieve_dir}/%d/%n/scripts;active={sieve_dir}/%d/%n/active.sieve"
    )

    master_user_block = ""
    if dovecot.master_user:
        master_user_block = """
# Master user. Lets Lightr open any mailbox for the API and the
# `lightr mailbox` commands without holding users' own passwords.
#
# The matching /etc/dovecot/master-users file is generated and hashed
# by Lightr -- do not edit it by hand, and do not add users to it.
passdb {
  driver = passwd-file
  args = /etc/dovecot/master-users
  master = yes
  result_success = continue
}
"""

    return f"""#
# Generated by Lightr. Do not edit -- regenerate with:
#     lightr dovecot config
#
# Install as /etc/dovecot/conf.d/{CONF_NAME} and restart dovecot.
#

protocols = imap lmtp

#
# Storage: Maildir, one file per message, never modified after write.
# mail_attachment_dir is deliberately NOT set -- single-instance
# attachment storage is deprecated and loses attachments.
#
mail_location = maildir:~/Maildir
mail_home = {maildir}/%d/%n
mail_uid = lightr
mail_gid = lightr
first_valid_uid = 1000

namespace inbox {{
  inbox = yes
  separator = /
  mailbox Sent {{
    special_use = \\Sent
    auto = subscribe
  }}
  mailbox Drafts {{
    special_use = \\Drafts
    auto = subscribe
  }}
  mailbox Trash {{
    special_use = \\Trash
    auto = subscribe
  }}
  mailbox Junk {{
    special_use = \\Junk
    auto = subscribe
  }}
  mailbox Archive {{
    special_use = \\Archive
    auto = subscribe
  }}
}}

#
# Authentication: everything goes through Lightr, so offloaded
# providers work for IMAP as well as for SMTP and the API.
#
auth_mechanisms = plain login
disable_plaintext_auth = {"no" if dovecot.imap_use_tls is False else "yes"}

#
# Authentication cache. Mail clients reconnect constantly, and every
# reconnect is an HTTP call into Lightr -- which, for an account backed
# by LDAP or an OIDC provider, is a further call out to that provider.
# Caching in front of all of it is what keeps IMAP responsive.
#
# The TTL is deliberately short, and `lightr account passwd` flushes
# the entry it changed, so a password change takes effect at once
# rather than whenever the cache happens to expire.
#
auth_cache_size = 10M
auth_cache_ttl = 5 mins
auth_cache_negative_ttl = 30 secs

mail_plugins = $mail_plugins quota

passdb {{
  driver = lua
  args = file={lua_path.as_posix()} blocking=yes
}}

userdb {{
  driver = lua
  args = file={lua_path.as_posix()} blocking=yes
}}
{master_user_block}
#
# LMTP: how Lightr delivers. Sieve runs here, using the headers
# Lightr injects during its own spam and authentication analysis.
#
service lmtp {{
  unix_listener {lmtp_listener} {{
    mode = 0600
    user = lightr
    group = lightr
  }}
}}

protocol lmtp {{
  mail_plugins = $mail_plugins sieve
}}

plugin {{
  sieve = {sieve_setting}
  sieve_extensions = +relational +comparator-i;ascii-numeric +imap4flags +mailbox +body

  quota = maildir:User quota
  quota_status_success = DUNNO
  quota_status_nouser = DUNNO
  quota_status_overquota = "552 5.2.2 Mailbox is full"
}}

#
# IMAP, for mail clients.
#
service imap-login {{
  inet_listener imap {{
    port = {dovecot.imap_port}
  }}
  inet_listener imaps {{
    port = 993
    ssl = yes
  }}
}}
"""


def generate(cfg: Config, *, api_base_url: str | None = None) -> list[GeneratedFile]:
    """Every file an operator needs to write."""
    base = api_base_url or _default_api_url(cfg)
    lua_path = Path("/etc/dovecot") / LUA_SCRIPT_NAME

    return [
        GeneratedFile(
            path=Path("/etc/dovecot/conf.d") / CONF_NAME,
            content=dovecot_conf(cfg, lua_path),
        ),
        GeneratedFile(
            path=lua_path,
            content=lua_script(cfg, base),
            # Carries the internal key. Dovecot's auth process reads it
            # as the dovecot user, so owner-only would leave the auth
            # process dead on arrival: "passdb-lua: initialization
            # failed: cannot open ...: Permission denied".
            mode=0o640,
            group=DOVECOT_GROUP,
        ),
    ]


def _default_api_url(cfg: Config) -> str:
    """Where Dovecot should reach Lightr.

    Always loopback: these endpoints see plaintext passwords and must
    never be reachable off the host.
    """
    addr = cfg.http.addr
    port = addr.rsplit(":", 1)[-1] if ":" in addr else "8080"
    return f"http://127.0.0.1:{port}"


__all__ = [
    "CONF_NAME",
    "LUA_SCRIPT_NAME",
    "DovecotConfigError",
    "GeneratedFile",
    "dovecot_conf",
    "generate",
    "generate_internal_key",
    "lua_script",
]
