"""Generating Dovecot's configuration.

Lightr owns this configuration rather than documenting it, because
"install the package and it works" is the difference between a mail
engine and a pile of parts. The generated files are reviewed as
carefully as the Python: they decide where mail is stored and who may
read it.

Two artefacts:

``dovecot.conf``
    A drop-in for ``/etc/dovecot/conf.d/``, wiring Maildir, LMTP,
    Sieve, quota, and the Lua auth backend.

``lightr-auth.lua``
    The passdb/userdb script. It calls Lightr's internal endpoints so
    that IMAP logins go through the same authentication path as
    everything else -- which is what makes LDAP/OAuth2/OIDC offload
    work for IMAP without a second implementation.
"""

from __future__ import annotations

import re
import secrets
from dataclasses import dataclass
from pathlib import Path

from lightr.config import Config
from lightr.dovecot import checkpassword, userdb

CONF_NAME = "99-lightr.conf"

#: How long mail stays in Trash and Junk before Dovecot removes it.
TRASH_RETENTION = "30d"

#: Dovecot's SQL userdb description.
USERDB_CONF_PATH = Path("/etc/dovecot/lightr-userdb.conf.ext")


class DovecotConfigError(ValueError):
    """The configuration could not be generated."""


#: Dovecot's auth process runs as this user, and has to read the files
#: that carry the credentials it authenticates with.
DOVECOT_GROUP = "dovecot"


@dataclass(frozen=True, slots=True)
class GeneratedFile:
    path: Path
    content: str
    mode: int = 0o644
    group: str | None = None

    @property
    def is_secret(self) -> bool:
        """Whether the file carries a credential.

        Owner-plus-group, not owner-only: Dovecot's auth process runs
        as the dovecot user, so a file it must read cannot be 0600
        root:root. Restricting it to the group is the tightest setting
        that still works.
        """
        return not self.mode & 0o007


def generate_internal_key() -> str:
    """A shared secret for the Lua script to present to Lightr."""
    return secrets.token_urlsafe(32)


def dovecot_conf(cfg: Config, lua_path: Path | None = None) -> str:
    """The Dovecot drop-in.

    ``lua_path`` is accepted and ignored: the Lua passdb is gone, and
    keeping the parameter means an old call site fails a test rather
    than a server.

    Maildir with no ``mail_attachment_dir``: single-instance attachment
    storage is deprecated and its failure mode is missing attachments,
    which is the worst outcome this engine can have.
    """
    del lua_path
    dovecot = cfg.dovecot
    maildir = dovecot.maildir_root.as_posix()
    checkpassword_path = checkpassword.SCRIPT_PATH.as_posix()
    userdb_conf_path = USERDB_CONF_PATH.as_posix()
    # Named relative to Dovecot's base_dir, not as an absolute path.
    # Dovecot's stock 10-master.conf already declares `unix_listener
    # lmtp`; an absolute path here resolves to the same socket but
    # counts as a second declaration, and Dovecot refuses to start with
    # "duplicate listener". The relative name merges with the stock one
    # instead, which is what we want -- we are only changing its mode
    # and ownership.
    lmtp_socket = (
        dovecot.lmtp_socket.as_posix() if dovecot.lmtp_socket else "/run/dovecot/lmtp"
    )
    lmtp_listener = Path(lmtp_socket).name if lmtp_socket.startswith(
        ("/run/dovecot/", "/var/run/dovecot/")
    ) else lmtp_socket

    sieve_dir = dovecot.sieve_dir.as_posix()
    # Dovecot requires this on a single line, however long it gets.
    sieve_setting = (
        f"file:{sieve_dir}/%d/%n/scripts;active={sieve_dir}/%d/%n/active.sieve"
    )
    spam_script = spam_script_path(cfg).as_posix()

    master_user_block = ""
    master_separator = ""
    if dovecot.master_user:
        master_user_block = """
# Master user. Lets Lightr open any mailbox for the API and the
# `lightr mailbox` commands without holding users' own passwords.
#
# The matching /etc/dovecot/master-users file is generated and hashed
# by Lightr -- do not edit it by hand, and do not add users to it.
passdb {
  driver = passwd-file
  args = /etc/dovecot/master-users
  master = yes
  result_success = continue
}
"""
        # Without this, Dovecot never splits "user*master" -- it looks
        # the whole string up as one username, fails, and the master
        # user is silently inert. Every mailbox read goes through it,
        # so the separator is not optional wherever it is configured.
        master_separator = "auth_master_user_separator = *"

    return f"""#
# Generated by Lightr. Do not edit -- regenerate with:
#     lightr dovecot config
#
# Install as /etc/dovecot/conf.d/{CONF_NAME} and restart dovecot.
#

protocols = imap lmtp

#
# Storage: Maildir, one file per message, never modified after write.
# mail_attachment_dir is deliberately NOT set -- single-instance
# attachment storage is deprecated and loses attachments.
#
mail_location = maildir:~/Maildir
mail_home = {maildir}/%d/%n
mail_uid = lightr
mail_gid = lightr
first_valid_uid = 1000

namespace inbox {{
  inbox = yes
  separator = /
  mailbox Sent {{
    special_use = \\Sent
    auto = subscribe
  }}
  mailbox Drafts {{
    special_use = \\Drafts
    auto = subscribe
  }}
  # Trash and Junk empty themselves. Without this they only grow, and
  # count against the quota, until someone remembers to empty them.
  mailbox Trash {{
    special_use = \\Trash
    auto = subscribe
    autoexpunge = {TRASH_RETENTION}
  }}
  mailbox Junk {{
    special_use = \\Junk
    auto = subscribe
    autoexpunge = {TRASH_RETENTION}
  }}
  mailbox Archive {{
    special_use = \\Archive
    auto = subscribe
  }}
}}

#
# Authentication: everything goes through Lightr, so offloaded
# providers work for IMAP as well as for SMTP and the API.
#
auth_mechanisms = plain login
{master_separator}
disable_plaintext_auth = {"no" if dovecot.imap_use_tls is False else "yes"}

{_ssl_settings(cfg)}

#
# Authentication cache. Mail clients reconnect constantly, and every
# reconnect is an HTTP call into Lightr -- which, for an account backed
# by LDAP or an OIDC provider, is a further call out to that provider.
# Caching in front of all of it is what keeps IMAP responsive.
#
# The TTL is deliberately short, and `lightr account passwd` flushes
# the entry it changed, so a password change takes effect at once
# rather than whenever the cache happens to expire.
#
auth_cache_size = 10M
auth_cache_ttl = 5 mins
auth_cache_negative_ttl = 30 secs

mail_plugins = $mail_plugins quota

#
# What mail clients rely on. imap_quota answers GETQUOTAROOT, which is
# how Thunderbird, Apple Mail and K-9 show "3.1 GB of 5 GB". The list
# index keeps LIST and STATUS fast with many folders, and is what
# autoexpunge uses to find old mail without scanning every message.
#
protocol imap {{
  mail_plugins = $mail_plugins imap_quota
  mail_max_userip_connections = 20
}}
mailbox_list_index = yes

#
# passdb: an external program, not Lua over HTTP. `dovecot.http` only
# exists in Dovecot 2.4, and Debian 12 and Ubuntu 22.04 both ship 2.3
# with no HTTP support compiled into Lua at all -- every login failed
# with "attempt to index a nil value (field 'http')". checkpassword
# needs nothing compiled in and works on every Dovecot there is.
#
# The script still calls Lightr, so offloaded providers (LDAP, OIDC, a
# webhook) keep working through the one authentication path.
#
passdb {{
  driver = checkpassword
  args = {checkpassword_path}
}}

#
# userdb: straight SQL. Where a mailbox lives is always Lightr's own
# answer, never an offloaded provider's, so this needs no HTTP -- and
# LMTP looks a user up without ever authenticating as them, which
# `prefetch` cannot serve.
#
userdb {{
  driver = sql
  args = {userdb_conf_path}
}}
{master_user_block}
#
# The checkpassword program runs under this service. It talks to
# Lightr over loopback, so it needs no privileges of its own.
#
service auth {{
  unix_listener auth-userdb {{
    mode = 0600
    user = lightr
    group = lightr
  }}
}}

#
# LMTP: how Lightr delivers. Sieve runs here, using the headers
# Lightr injects during its own spam and authentication analysis.
#
service lmtp {{
  unix_listener {lmtp_listener} {{
    mode = 0600
    user = lightr
    group = lightr
  }}
}}

protocol lmtp {{
  mail_plugins = $mail_plugins sieve
}}

plugin {{
  sieve = {sieve_setting}
  # Runs before each mailbox's own script: mail Lightr marked as spam
  # for a domain whose policy is junk goes to Junk, and stops there.
  sieve_before = {spam_script}
  sieve_extensions = +relational +comparator-i;ascii-numeric +imap4flags +mailbox +body

  quota = maildir:User quota
  quota_status_success = DUNNO
  quota_status_nouser = DUNNO
  quota_status_overquota = "552 5.2.2 Mailbox is full"
}}

#
# IMAP, for mail clients.
#
service imap-login {{
  inet_listener imap {{
    port = {dovecot.imap_port}
  }}
  inet_listener imaps {{
    port = 993
    ssl = yes
  }}
}}
"""


def generate(cfg: Config, *, api_base_url: str | None = None) -> list[GeneratedFile]:
    """Every file an operator needs to write."""
    base = api_base_url or _default_api_url(cfg)
    if not cfg.dovecot.internal_key:
        raise DovecotConfigError(
            "no internal auth key is set. Run: lightr setup"
        )

    return [
        GeneratedFile(
            path=Path("/etc/dovecot/conf.d") / CONF_NAME,
            content=dovecot_conf(cfg),
        ),
        GeneratedFile(
            path=checkpassword.SCRIPT_PATH,
            content=checkpassword.script(base, cfg.dovecot.internal_key),
            # Executable, and readable by the auth process that runs it.
            # It carries the internal key, so nothing wider than that.
            mode=0o750,
            group=DOVECOT_GROUP,
        ),
        GeneratedFile(
            path=USERDB_CONF_PATH,
            content=userdb.userdb_conf(cfg),
            # Carries the database password.
            mode=0o640,
            group=DOVECOT_GROUP,
        ),
        GeneratedFile(path=spam_script_path(cfg), content=spam_script()),
    ]


_HOSTNAME = re.compile(
    r"^(?=.{1,253}$)"
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?"
    r"(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$"
)


def _present(*paths: Path | None) -> bool:
    """Whether every file exists.

    Checked when the configuration is generated, because Lightr's
    default tls paths are placeholders under data_dir -- and a Dovecot
    pointed at a certificate that is not there refuses to start, taking
    every mailbox down with it.
    """
    return all(path is not None and path.is_file() for path in paths)


def _ssl_settings(cfg: Config) -> str:
    """Dovecot's certificates, taken from Lightr's own `tls` settings.

    Without this Dovecot presents whatever its stock 10-ssl.conf names
    -- on Debian and Ubuntu a self-signed snakeoil certificate -- so
    every mail client warns on IMAPS while Lightr's SMTP presents the
    real one. One set of certificates, configured once, for both.

    `domain_certs` become `local_name` blocks, so a client connecting to
    mail.example.com is shown that name's certificate.
    """
    tls = cfg.tls
    if not _present(tls.cert_file, tls.key_file):
        return (
            "# Lightr's tls: certificate was not found, so Dovecot presents\n"
            "# whatever its own 10-ssl.conf names. Set tls.cert_file and\n"
            "# tls.key_file to a real certificate, then run: lightr setup"
        )

    lines = [
        "#",
        "# TLS for IMAP, from Lightr's tls: settings.",
        "#",
        f"ssl_cert = <{tls.cert_file.as_posix()}",
        f"ssl_key = <{tls.key_file.as_posix()}",
        "ssl_min_protocol = TLSv1.2",
    ]
    for name, cert in sorted(tls.domain_certs.items()):
        hostname = name.strip().lower()
        # The name goes into a config block unquoted; anything that is
        # not a plain hostname could close the block and add settings.
        if not _HOSTNAME.match(hostname):
            raise DovecotConfigError(f"tls.domain_certs has an invalid hostname: {name!r}")
        if not _present(cert.cert_file, cert.key_file):
            lines.append(f"# {hostname}: certificate not found, so not served")
            continue
        lines += [
            f"local_name {hostname} {{",
            f"  ssl_cert = <{cert.cert_file.as_posix()}",
            f"  ssl_key = <{cert.key_file.as_posix()}",
            "}",
        ]
    return "\n".join(lines)


#: The server-wide spam script, under sieve_dir. There rather than in
#: /etc/dovecot because LMTP runs as the mail user and writes the
#: compiled form next to the script; a directory it cannot write means
#: recompiling on every delivery. `_global` cannot collide with a
#: mailbox's directory: domain names cannot contain an underscore
#: at the start and always contain a dot.
SPAM_SCRIPT = Path("_global") / "spam.sieve"


def spam_script_path(cfg: Config) -> Path:
    return cfg.dovecot.sieve_dir / SPAM_SCRIPT


def spam_script() -> str:
    """File mail marked for Junk into Junk.

    Compiled by the same generator as mailbox filter rules, so its
    syntax is the syntax already tested there.
    """
    from lightr.dovecot.sieve import (
        HEADER_SPAM_ACTION,
        SPAM_ACTION_JUNK,
        Action,
        Condition,
        Field,
        Operator,
        Rule,
        compile_script,
    )

    rule = Rule(
        name="File spam into Junk",
        conditions=[
            Condition(Field.HEADER, Operator.EQUALS, SPAM_ACTION_JUNK,
                      header=HEADER_SPAM_ACTION)
        ],
        actions=[(Action.FILE_INTO, "Junk"), (Action.STOP, "")],
    )
    # Script.render's header is written for mailbox filter scripts; this
    # one is rewritten by `lightr setup`, and an edit shows up as drift.
    body = compile_script([rule]).render().split("\n\n", 1)[1]
    return (
        "# Generated by Lightr. Do not edit -- `lightr setup` rewrites it,\n"
        "# and `lightr serve` reports any change to it as drift.\n\n" + body
    )


def _default_api_url(cfg: Config) -> str:
    """Where Dovecot should reach Lightr.

    Always loopback: these endpoints see plaintext passwords and must
    never be reachable off the host.
    """
    addr = cfg.http.addr
    port = addr.rsplit(":", 1)[-1] if ":" in addr else "8080"
    return f"http://127.0.0.1:{port}"


__all__ = [
    "CONF_NAME",
    "DOVECOT_GROUP",
    "USERDB_CONF_PATH",
    "DovecotConfigError",
    "GeneratedFile",
    "dovecot_conf",
    "generate",
    "generate_internal_key",
]
