"""Compiling Lightr filter rules into Sieve scripts.

Under Dovecot, Lightr stops *running* a filter engine and starts
emitting one. Rules split in two:

* conditions Sieve can evaluate itself -- from, to, cc, subject,
  header, size -- become native Sieve tests
* conditions only Lightr can evaluate -- spam score, SPF/DKIM/DMARC
  results, attachment presence -- are computed before LMTP and encoded
  as headers, which the generated script then tests

So ``spam_score > 4`` becomes a test against ``X-Spam-Score``, written
by Lightr's own analysis on the way in. The rule author never sees the
difference.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from enum import StrEnum

# Headers Lightr injects pre-LMTP so Sieve can test its analysis.
HEADER_SPAM_SCORE = "X-Spam-Score"
HEADER_SPAM_FLAG = "X-Spam-Flag"
HEADER_AUTH_RESULTS = "Authentication-Results"
HEADER_HAS_ATTACHMENT = "X-Lightr-Has-Attachment"


class Field(StrEnum):
    FROM = "from"
    TO = "to"
    CC = "cc"
    SUBJECT = "subject"
    BODY = "body"
    HEADER = "header"
    ATTACHMENT = "attachment"
    SIZE = "size"
    SPAM_SCORE = "spam_score"
    SPF_RESULT = "spf_result"
    DKIM_RESULT = "dkim_result"
    DMARC_RESULT = "dmarc_result"


class Operator(StrEnum):
    EQUALS = "equals"
    CONTAINS = "contains"
    STARTS_WITH = "starts_with"
    ENDS_WITH = "ends_with"
    MATCHES = "matches"
    GREATER_THAN = "gt"
    LESS_THAN = "lt"


class Action(StrEnum):
    FILE_INTO = "file_into"
    DISCARD = "discard"
    REJECT = "reject"
    REDIRECT = "redirect"
    MARK_READ = "mark_read"
    FLAG = "flag"
    STOP = "stop"


class MatchType(StrEnum):
    ALL = "all"
    ANY = "any"


#: Fields Lightr must evaluate itself, mapped to the header it writes.
LIGHTR_EVALUATED: dict[Field, str] = {
    Field.SPAM_SCORE: HEADER_SPAM_SCORE,
    Field.SPF_RESULT: HEADER_AUTH_RESULTS,
    Field.DKIM_RESULT: HEADER_AUTH_RESULTS,
    Field.DMARC_RESULT: HEADER_AUTH_RESULTS,
    Field.ATTACHMENT: HEADER_HAS_ATTACHMENT,
}

_MATCH_KEYWORD: dict[Operator, str] = {
    Operator.EQUALS: ':is',
    Operator.CONTAINS: ':contains',
    Operator.STARTS_WITH: ':matches',
    Operator.ENDS_WITH: ':matches',
    Operator.MATCHES: ':matches',
}


class SieveError(ValueError):
    """A rule could not be compiled into Sieve."""


@dataclass(frozen=True, slots=True)
class Condition:
    field: Field
    operator: Operator
    value: str
    header: str | None = None  # only for Field.HEADER


@dataclass(frozen=True, slots=True)
class Rule:
    name: str
    conditions: Sequence[Condition]
    actions: Sequence[tuple[Action, str]]
    match_type: MatchType = MatchType.ALL
    priority: int = 100
    stop_on_match: bool = False
    is_active: bool = True


@dataclass
class Script:
    """A generated Sieve script."""

    body: str
    requires: set[str] = field(default_factory=set)

    def render(self) -> str:
        header = (
            "# Generated by Lightr. Do not edit -- changes are\n"
            "# overwritten whenever filter rules change.\n"
        )
        require = ""
        if self.requires:
            names = ", ".join(f'"{r}"' for r in sorted(self.requires))
            require = f"require [{names}];\n\n"
        return f"{header}\n{require}{self.body}"


def quote(value: str) -> str:
    """Quote a Sieve string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _escape_glob(value: str) -> str:
    """Escape Sieve ``:matches`` wildcards in a literal fragment."""
    return value.replace("\\", "\\\\").replace("*", "\\*").replace("?", "\\?")


def _header_test(header: str, op: Operator, value: str) -> str:
    """A ``header`` test for one of the address-ish fields."""
    if op is Operator.STARTS_WITH:
        pattern = _escape_glob(value) + "*"
    elif op is Operator.ENDS_WITH:
        pattern = "*" + _escape_glob(value)
    elif op is Operator.MATCHES:
        pattern = value
    else:
        pattern = value
    keyword = _MATCH_KEYWORD.get(op)
    if keyword is None:
        raise SieveError(f"operator {op} is not valid for header {header!r}")
    return f"header {keyword} {quote(header)} {quote(pattern)}"


def _numeric_header_test(header: str, op: Operator, value: str) -> tuple[str, set[str]]:
    """Compare a numeric header, e.g. ``X-Spam-Score > 4``."""
    try:
        float(value)
    except ValueError as exc:
        raise SieveError(f"{header} needs a numeric value, got {value!r}") from exc
    comparator = "gt" if op is Operator.GREATER_THAN else "lt"
    if op not in (Operator.GREATER_THAN, Operator.LESS_THAN):
        raise SieveError(f"operator {op} is not valid for numeric header {header!r}")
    test = (
        f'header :value "{comparator}" :comparator "i;ascii-numeric" '
        f"{quote(header)} {quote(value)}"
    )
    return test, {"relational", "comparator-i;ascii-numeric"}


def compile_condition(cond: Condition) -> tuple[str, set[str]]:
    """Compile one condition into a Sieve test plus its requires."""
    match cond.field:
        case Field.FROM | Field.TO | Field.CC | Field.SUBJECT:
            return _header_test(cond.field.value.capitalize(), cond.operator, cond.value), set()

        case Field.HEADER:
            if not cond.header:
                raise SieveError("a 'header' condition needs a header name")
            return _header_test(cond.header, cond.operator, cond.value), set()

        case Field.BODY:
            if cond.operator not in (Operator.CONTAINS, Operator.MATCHES):
                raise SieveError(f"operator {cond.operator} is not valid for a body test")
            keyword = ":contains" if cond.operator is Operator.CONTAINS else ":matches"
            return f"body :text {keyword} {quote(cond.value)}", {"body"}

        case Field.SIZE:
            try:
                size = int(cond.value)
            except ValueError as exc:
                raise SieveError(f"size needs an integer, got {cond.value!r}") from exc
            over = ":over" if cond.operator is Operator.GREATER_THAN else ":under"
            if cond.operator not in (Operator.GREATER_THAN, Operator.LESS_THAN):
                raise SieveError(f"operator {cond.operator} is not valid for size")
            return f"size {over} {size}", set()

        case Field.SPAM_SCORE:
            return _numeric_header_test(HEADER_SPAM_SCORE, cond.operator, cond.value)

        case Field.SPF_RESULT | Field.DKIM_RESULT | Field.DMARC_RESULT:
            # Lightr writes a single Authentication-Results header; test
            # for the mechanism and verdict together.
            method = cond.field.value.removesuffix("_result")
            fragment = f"{method}={cond.value}"
            return (
                f"header :contains {quote(HEADER_AUTH_RESULTS)} {quote(fragment)}",
                set(),
            )

        case Field.ATTACHMENT:
            # Presence only. Lightr sets the header during analysis
            # because Sieve cannot inspect MIME structure portably.
            want = cond.value.lower() not in ("false", "no", "0", "")
            test = f'header :is {quote(HEADER_HAS_ATTACHMENT)} "yes"'
            return (test if want else f"not {test}"), set()

    raise SieveError(f"unsupported condition field: {cond.field}")


def compile_action(action: Action, argument: str) -> tuple[str, set[str]]:
    """Compile one action into a Sieve command plus its requires."""
    match action:
        case Action.FILE_INTO:
            folder = argument or "INBOX"
            return f"fileinto :create {quote(folder)};", {"fileinto", "mailbox"}
        case Action.DISCARD:
            return "discard;", set()
        case Action.REJECT:
            reason = argument or "Message rejected by policy"
            return f"reject {quote(reason)};", {"reject"}
        case Action.REDIRECT:
            if not _is_address(argument):
                raise SieveError(f"redirect needs an email address, got {argument!r}")
            return f"redirect {quote(argument)};", set()
        case Action.MARK_READ:
            return 'setflag "\\\\Seen";', {"imap4flags"}
        case Action.FLAG:
            return 'addflag "\\\\Flagged";', {"imap4flags"}
        case Action.STOP:
            return "stop;", set()

    raise SieveError(f"unsupported action: {action}")


_ADDRESS = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def _is_address(value: str) -> bool:
    return bool(_ADDRESS.match(value.strip()))


def compile_rule(rule: Rule) -> tuple[str, set[str]]:
    """Compile a single rule into an ``if`` block."""
    if not rule.conditions:
        raise SieveError(f"rule {rule.name!r} has no conditions")
    if not rule.actions:
        raise SieveError(f"rule {rule.name!r} has no actions")

    requires: set[str] = set()
    tests: list[str] = []
    for cond in rule.conditions:
        test, needed = compile_condition(cond)
        tests.append(test)
        requires |= needed

    joiner = "allof" if rule.match_type is MatchType.ALL else "anyof"
    condition = tests[0] if len(tests) == 1 else f"{joiner} (\n        " + ",\n        ".join(
        tests
    ) + "\n    )"

    body: list[str] = []
    for action, argument in rule.actions:
        command, needed = compile_action(action, argument)
        body.append(f"    {command}")
        requires |= needed
    if rule.stop_on_match and not any(a is Action.STOP for a, _ in rule.actions):
        body.append("    stop;")

    lines = [f"# {rule.name}", f"if {condition} {{", *body, "}"]
    return "\n".join(lines), requires


def compile_script(rules: Iterable[Rule]) -> Script:
    """Compile an account's active rules into one script.

    Rules run in priority order -- lowest number first, matching the
    Go engine, where priority 0 meant 'evaluate this before anything
    else'.
    """
    active = sorted(
        (r for r in rules if r.is_active), key=lambda r: (r.priority, r.name)
    )
    if not active:
        return Script(body="# No active rules.\n")

    blocks: list[str] = []
    requires: set[str] = set()
    for rule in active:
        block, needed = compile_rule(rule)
        blocks.append(block)
        requires |= needed

    return Script(body="\n\n".join(blocks) + "\n", requires=requires)


__all__ = [
    "LIGHTR_EVALUATED",
    "Action",
    "Condition",
    "Field",
    "MatchType",
    "Operator",
    "Rule",
    "Script",
    "SieveError",
    "compile_action",
    "compile_condition",
    "compile_rule",
    "compile_script",
]
