"""Dovecot's userdb, as a direct SQL query.

"Where does this mailbox live, and what is its quota" is always
answered by Lightr's own database. It is never answered by an offloaded
provider -- LDAP may say whether a password is right, but it does not
know where this server keeps the Maildir. So unlike the passdb, the
userdb needs no HTTP at all, and a direct query is both faster and one
less moving part.

It also has to work *without* a passdb lookup. LMTP delivers to an
address nobody has authenticated as, so ``prefetch`` -- which reuses
fields the passdb returned -- cannot serve it. That rules out the
obvious shortcut and leaves a real userdb.

The connect string carries the database password, so the generated file
is owner-and-group only, readable by Dovecot and nobody else.
"""

from __future__ import annotations

from lightr.config import Config, DatabaseDriver


class UserdbError(ValueError):
    """The userdb could not be described to Dovecot."""


#: Dovecot expands %n to the local part and %d to the domain. They are
#: passed as SQL parameters via Dovecot's own quoting, not interpolated
#: here -- Dovecot escapes %n/%d for the driver it is using.
USER_QUERY = (
    "SELECT '{maildir}/%d/%n' AS home, "
    "'maildir:{maildir}/%d/%n' AS mail, "
    "'{user}' AS uid, '{group}' AS gid"
    "{quota} "
    "FROM accounts a JOIN domains d ON a.domain_id = d.id "
    "WHERE a.local_part = '%n' AND d.name = '%d'"
)

#: Quota is optional: an account with none should not get a rule at all,
#: or Dovecot enforces a limit of zero.
QUOTA_POSTGRES = (
    ", CASE WHEN a.quota_bytes > 0 "
    "THEN '*:bytes=' || a.quota_bytes ELSE NULL END AS quota_rule"
)
QUOTA_SQLITE = (
    ", CASE WHEN a.quota_bytes > 0 "
    "THEN '*:bytes=' || a.quota_bytes ELSE NULL END AS quota_rule"
)

ITERATE_QUERY = (
    "SELECT a.local_part AS username, d.name AS domain "
    "FROM accounts a JOIN domains d ON a.domain_id = d.id"
)


def connect_string(cfg: Config) -> str:
    """Dovecot's own connection syntax for this database.

    Deliberately not the SQLAlchemy URL: Dovecot wants libpq keywords,
    and handing it a URL produces a connection error at delivery time
    rather than a clear one now.
    """
    database = cfg.database

    if database.driver is DatabaseDriver.SQLITE:
        if database.path is None:
            raise UserdbError("database.path is not set for the sqlite driver")
        return database.path.as_posix()

    if not database.dsn:
        raise UserdbError(
            "database.dsn is required for the postgres driver -- Dovecot needs "
            "its own connection to answer userdb lookups"
        )
    return _libpq(database.dsn)


def _libpq(dsn: str) -> str:
    """Turn a postgresql:// URL into libpq keyword form.

    Dovecot's pgsql driver takes ``host=... dbname=...``, not a URL.
    """
    from urllib.parse import unquote, urlparse

    parsed = urlparse(dsn)
    if parsed.scheme.startswith("postgres"):
        parts = []
        if parsed.hostname:
            parts.append(f"host={parsed.hostname}")
        if parsed.port:
            parts.append(f"port={parsed.port}")
        database = (parsed.path or "").lstrip("/")
        if database:
            parts.append(f"dbname={database}")
        if parsed.username:
            parts.append(f"user={unquote(parsed.username)}")
        if parsed.password:
            parts.append(f"password={unquote(parsed.password)}")
        return " ".join(parts)

    # Already keyword form, or something we should pass through rather
    # than mangle.
    return dsn


def driver_name(cfg: Config) -> str:
    return "sqlite" if cfg.database.driver is DatabaseDriver.SQLITE else "pgsql"


def package_name(cfg: Config) -> str:
    """The Debian package that provides this driver.

    Named in errors, because a missing one fails at delivery time with
    "Unknown database driver" and nothing pointing at the fix.
    """
    return f"dovecot-{driver_name(cfg)}"


def userdb_conf(cfg: Config) -> str:
    """The ``lightr-userdb.conf.ext`` Dovecot reads."""
    driver = driver_name(cfg)
    quota = QUOTA_SQLITE if driver == "sqlite" else QUOTA_POSTGRES
    query = USER_QUERY.format(
        maildir=cfg.dovecot.maildir_root.as_posix(),
        user="lightr",
        group="lightr",
        quota=quota,
    )

    return f"""#
# Generated by Lightr. Do not edit -- regenerate with:
#     lightr dovecot install
#
# Dovecot answers "where does this mailbox live" straight from Lightr's
# database. It needs no HTTP: an offloaded provider decides whether a
# password is right, never where the Maildir is.
#
# This file carries the database password. It is owner-and-group only,
# and the group is dovecot.
#
driver = {driver}
connect = {connect_string(cfg)}

user_query = {query}

iterate_query = {ITERATE_QUERY}
"""


__all__ = [
    "ITERATE_QUERY",
    "USER_QUERY",
    "UserdbError",
    "connect_string",
    "driver_name",
    "package_name",
    "userdb_conf",
]
