"""Internal endpoints for Dovecot.

Dovecot's passdb and userdb call these over HTTP from a Lua script.
Routing IMAP authentication through Lightr -- rather than pointing
Dovecot's SQL passdb straight at ``accounts.password_hash`` -- is what
makes offloaded auth (LDAP, OAuth2, OIDC, webhook) work for IMAP too:
there is one authentication path, not two.

These routes are **not** part of the public API. They see plaintext
passwords, so:

* bind them to localhost or a unix socket, never a public interface
* never log the request body
* they authenticate with a shared secret, not an API key, because
  Dovecot is a service and not an operator

The matching Dovecot configuration is generated by
``lightr dovecot config``.
"""

from __future__ import annotations

import hmac
import json
import logging
from typing import Any

from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.routing import Route

from lightr.auth import TEMPORARY_FAILURES, Authenticator, AuthFailure
from lightr.dovecot.maildir import layout_for
from lightr.repo import AccountRepo

log = logging.getLogger("lightr.auth")

#: Header Dovecot's Lua script sends the shared secret in.
AUTH_HEADER = "X-Lightr-Internal-Key"

#: Failures that mean "Lightr could not tell", as opposed to "the
#: credentials were wrong". These come back as 503, which the generated
#: Lua turns into PASSDB_RESULT_INTERNAL_FAILURE -- so an offloaded
#: provider being down makes Dovecot say "try later" rather than
#: telling every user their password is wrong.
_TEMPORARY = TEMPORARY_FAILURES


def _refuse(reason: str, status: int = 401) -> JSONResponse:
    return JSONResponse({"status": "fail", "reason": reason}, status)


def _check_secret(request: Request) -> Response | None:
    """Verify the shared secret, in constant time."""
    expected = request.app.state.config.dovecot.internal_key
    if not expected:
        return _refuse("internal auth is not configured", 503)

    presented = request.headers.get(AUTH_HEADER, "")
    if not hmac.compare_digest(presented, expected):
        return _refuse("bad internal key", 403)
    return None


async def _body(request: Request) -> dict[str, Any]:
    try:
        parsed = await request.json()
    except (json.JSONDecodeError, ValueError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


async def passdb(request: Request) -> Response:
    """Authenticate an IMAP login for Dovecot.

    Never echoes the password, and returns the same shape whether the
    account is unknown or the password was wrong.
    """
    if refusal := _check_secret(request):
        return refusal

    body = await _body(request)
    username = str(body.get("username", "")).strip()
    password = str(body.get("password", ""))
    if not username or not password:
        return _refuse("username and password are required", 400)

    result = await Authenticator(request.state.conn).authenticate(username, password)
    if not result.ok:
        assert result.failure is not None
        if result.detail:
            # Logged here, never returned: whoever is logging in must
            # not learn which provider refused them or why.
            log.warning("auth failed for %s: %s", username, result.detail)
        status = 503 if result.failure in _TEMPORARY else 401
        return _refuse(result.failure.value, status)

    account = result.account
    assert account is not None
    return JSONResponse(
        {
            "status": "ok",
            "user": account.email,
            "home": account.maildir_path,
        }
    )


async def userdb(request: Request) -> Response:
    """Tell Dovecot where a mailbox lives and what quota it has.

    Dovecot calls this after authentication, and also on its own for
    LMTP delivery -- so it must work for an account that has never
    logged in.
    """
    if refusal := _check_secret(request):
        return refusal

    body = await _body(request)
    username = str(body.get("username", "")).strip()
    if not username:
        username = request.query_params.get("user", "").strip()
    if not username:
        return _refuse("username is required", 400)

    account = await AccountRepo(request.state.conn).find(username)
    if account is None:
        return _refuse(AuthFailure.NO_SUCH_ACCOUNT.value, 404)

    cfg = request.app.state.config
    email = account.email or username
    home = account.maildir_path or layout_for(cfg.dovecot.maildir_root, email).posix

    payload: dict[str, Any] = {
        "status": "ok",
        "user": email,
        "home": home,
        "mail": f"maildir:{home}",
    }
    if account.quota_bytes:
        # Dovecot's quota rule syntax. Lightr configures; Dovecot enforces.
        payload["quota_rule"] = f"*:bytes={account.quota_bytes}"

    return JSONResponse(payload)


INTERNAL_ROUTES: list[Route] = [
    Route("/internal/auth/verify", passdb, methods=["POST"]),
    Route("/internal/auth/user", userdb, methods=["POST", "GET"]),
]

#: Internal routes authenticate with the shared secret, not an API key,
#: so the API-key middleware must skip them.
INTERNAL_PATHS = frozenset(r.path for r in INTERNAL_ROUTES)


__all__ = ["AUTH_HEADER", "INTERNAL_PATHS", "INTERNAL_ROUTES", "passdb", "userdb"]
