package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// RenderAnnotatedYAML renders a full operator-facing config template with
// optional sections commented out so install-time configs are discoverable.
func RenderAnnotatedYAML(cfg *Config) (string, error) {
	if cfg == nil {
		cfg = Default()
	}
	clone := *cfg
	clone.normalize()

	var b strings.Builder
	b.WriteString("# Lightr configuration\n")
	b.WriteString("# Generated by lightr. Optional settings stay commented until you need them.\n")
	b.WriteString("#\n")
	b.WriteString("# SQLite to PostgreSQL switch-over:\n")
	b.WriteString("#   1. lightr data export --output lightr-export.yaml\n")
	b.WriteString("#   2. Change database.driver to postgres.\n")
	b.WriteString("#   3. Comment out database.path and uncomment database.dsn.\n")
	b.WriteString("#   4. Start lightr against PostgreSQL, then run:\n")
	b.WriteString("#      lightr data import lightr-export.yaml\n")
	b.WriteString("#\n")
	b.WriteString("# Port guide:\n")
	b.WriteString("#   smtp.addr           = port 25   (server-to-server receive)\n")
	b.WriteString("#   smtp.submission_addr= port 587  (authenticated client submission)\n")
	b.WriteString("#   imap.addr           = port 143  (IMAP with STARTTLS)\n")
	b.WriteString("#   imap.tls_addr       = port 993  (implicit TLS IMAP)\n\n")

	writeLine(&b, "", "data_dir", clone.DataDir)
	b.WriteString("\nserver:\n")
	b.WriteString("  # Node-level hostname used for EHLO/HELO and as the fallback mail host.\n")
	writeLine(&b, "  ", "hostname", clone.Server.Hostname)
	b.WriteString("  # Bind address for listeners on this machine.\n")
	writeLine(&b, "  ", "bind_address", clone.Server.BindAddress)

	b.WriteString("\ndatabase:\n")
	b.WriteString("  # Supported today: sqlite or postgres.\n")
	writeLine(&b, "  ", "driver", string(clone.Database.Driver))
	if clone.Database.Driver == DatabaseDriverPostgres {
		writeCommentedLine(&b, "  ", "path", firstNonEmpty(clone.Database.Path, filepathHint(clone.DataDir, "lightr.db")))
		writeLine(&b, "  ", "dsn", firstNonEmpty(clone.Database.DSN, "postgres://lightr:CHANGE_ME@127.0.0.1:5432/lightr?sslmode=require"))
	} else {
		writeLine(&b, "  ", "path", firstNonEmpty(clone.Database.Path, filepathHint(clone.DataDir, "lightr.db")))
		writeCommentedLine(&b, "  ", "dsn", "postgres://lightr:CHANGE_ME@127.0.0.1:5432/lightr?sslmode=require")
	}

	b.WriteString("\nhttp:\n")
	b.WriteString("  # Keep this on localhost unless you are intentionally exposing the admin API.\n")
	writeLine(&b, "  ", "addr", clone.HTTP.Addr)

	b.WriteString("\napi:\n")
	b.WriteString("  # Bootstrap key for admin and automation. Rotate after install if needed.\n")
	writeLine(&b, "  ", "key", clone.API.Key)
	writeLine(&b, "  ", "admin_key", clone.API.AdminKey)

	b.WriteString("\nsmtp:\n")
	b.WriteString("  # Inbound SMTP from other mail servers.\n")
	writeLine(&b, "  ", "addr", clone.SMTP.Addr)
	b.WriteString("  # Authenticated SMTP submission for users and apps.\n")
	writeLine(&b, "  ", "submission_addr", clone.SMTP.SubmissionAddr)
	b.WriteString("  # SMTP greeting/EHLO identity comes from server.hostname.\n")
	writeLine(&b, "  ", "max_message_bytes", clone.SMTP.MaxMessageBytes)
	writeLine(&b, "  ", "max_recipients", clone.SMTP.MaxRecipients)
	b.WriteString("  # Set true only for local development without TLS.\n")
	writeLine(&b, "  ", "allow_insecure", clone.SMTP.AllowInsecure)

	b.WriteString("\nimap:\n")
	b.WriteString("  # IMAP with STARTTLS.\n")
	writeLine(&b, "  ", "addr", clone.IMAP.Addr)
	b.WriteString("  # IMAP over implicit TLS.\n")
	writeLine(&b, "  ", "tls_addr", clone.IMAP.TLSAddr)
	b.WriteString("  # Set true only for local development without TLS.\n")
	writeLine(&b, "  ", "allow_insecure", clone.IMAP.AllowInsecure)

	b.WriteString("\ndkim:\n")
	b.WriteString("  # Default selector used when new domains auto-generate DKIM keys.\n")
	writeLine(&b, "  ", "selector", clone.DKIM.Selector)
	writeLine(&b, "  ", "key_bits", clone.DKIM.KeyBits)
	writeOptionalLine(&b, "  ", "private_key_path", clone.DKIM.PrivateKey, filepathHint(clone.DataDir, "dkim", "default.pem"))

	b.WriteString("\ntls:\n")
	b.WriteString("  # Default certificate used for SMTP/IMAP and as the SNI fallback certificate.\n")
	writeLine(&b, "  ", "cert_file", clone.TLS.CertFile)
	writeLine(&b, "  ", "key_file", clone.TLS.KeyFile)
	b.WriteString("  # Optional per-domain SNI certificates.\n")
	if len(clone.TLS.DomainCerts) == 0 {
		b.WriteString("  # domain_certs:\n")
		b.WriteString("  #   example.com:\n")
		b.WriteString("  #     cert_file: /etc/letsencrypt/live/mail.example.com/fullchain.pem\n")
		b.WriteString("  #     key_file: /etc/letsencrypt/live/mail.example.com/privkey.pem\n")
	} else {
		b.WriteString("  domain_certs:\n")
		for domainName, cert := range clone.TLS.DomainCerts {
			fmt.Fprintf(&b, "    %s:\n", domainName)
			writeLine(&b, "      ", "cert_file", cert.CertFile)
			writeLine(&b, "      ", "key_file", cert.KeyFile)
		}
	}

	b.WriteString("\nwebhook:\n")
	b.WriteString("  # Optional global delivery event webhook for all domains.\n")
	writeLine(&b, "  ", "enabled", clone.Webhook.Enabled)
	writeOptionalLine(&b, "  ", "url", clone.Webhook.URL, "https://example.com/lightr/events")

	b.WriteString("\nlogging:\n")
	writeLine(&b, "  ", "level", clone.Logging.Level)
	writeLine(&b, "  ", "file", clone.Logging.File)

	b.WriteString("\nspam:\n")
	writeLine(&b, "  ", "enabled", clone.Spam.Enabled)
	writeLine(&b, "  ", "suspicious_threshold", clone.Spam.SuspiciousThreshold)
	writeLine(&b, "  ", "junk_threshold", clone.Spam.JunkThreshold)
	writeLine(&b, "  ", "timeout_seconds", clone.Spam.TimeoutSeconds)
	if len(clone.Spam.DNSBLZones) == 0 {
		b.WriteString("  # dnsbl_zones:\n")
		b.WriteString("  #   - zen.spamhaus.org\n")
		b.WriteString("  #   - bl.spamcop.net\n")
	} else {
		b.WriteString("  dnsbl_zones:\n")
		for _, zone := range clone.Spam.DNSBLZones {
			writeListItem(&b, "    ", zone)
		}
	}
	writeOptionalLine(&b, "  ", "rspamd_url", clone.Spam.RspamdURL, "http://127.0.0.1:11334")
	writeOptionalLine(&b, "  ", "rspamd_password", clone.Spam.RspamdPassword, "CHANGE_ME")

	b.WriteString("\nsecurity:\n")
	b.WriteString("  # When true, SMTP/IMAP auth requires TLS.\n")
	writeLine(&b, "  ", "require_tls_for_auth", clone.Security.RequireTLSForAuth)

	return b.String(), nil
}

func WriteAnnotatedYAML(path string, cfg *Config) error {
	rendered, err := RenderAnnotatedYAML(cfg)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(rendered), 0600)
}

func writeLine(b *strings.Builder, indent, key string, value interface{}) {
	scalar, err := yamlScalar(value)
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(b, "%s%s: %s\n", indent, key, scalar)
}

func writeOptionalLine(b *strings.Builder, indent, key, value, placeholder string) {
	if strings.TrimSpace(value) == "" {
		writeCommentedLine(b, indent, key, placeholder)
		return
	}
	writeLine(b, indent, key, value)
}

func writeCommentedLine(b *strings.Builder, indent, key, value string) {
	scalar, err := yamlScalar(value)
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(b, "%s# %s: %s\n", indent, key, scalar)
}

func writeListItem(b *strings.Builder, indent string, value string) {
	scalar, err := yamlScalar(value)
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(b, "%s- %s\n", indent, scalar)
}

func yamlScalar(value interface{}) (string, error) {
	data, err := yaml.Marshal(value)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}

func filepathHint(parts ...string) string {
	filtered := make([]string, 0, len(parts))
	for _, part := range parts {
		if strings.TrimSpace(part) != "" {
			filtered = append(filtered, strings.TrimSpace(part))
		}
	}
	if len(filtered) == 0 {
		return ""
	}
	return filepath.Join(filtered...)
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}
